<?php

declare(strict_types=1);

namespace App\Service;

use App\Entity\Event;
use App\Entity\Reservation;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * Service for automatically creating and managing events based on reservations.
 *
 * When a reservation is created/updated, this service ensures that a corresponding
 * Event exists for that date. If no event exists, it creates a DRAFT event that
 * can later be finalized by a manager.
 */
class AutoEventService
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly EventGuestSyncService $guestSyncService,
        private readonly EventRepository $eventRepository,
    ) {
    }

    /**
     * Ensures an Event exists for the given date.
     * If no event exists, creates a new auto-generated DRAFT event.
     *
     * @return Event The existing or newly created event
     */
    public function ensureEventForDate(\DateTimeInterface $date): Event
    {
        // Normalize to date only (no time component)
        $dateOnly = \DateTime::createFromInterface($date)->setTime(0, 0, 0);

        // Check if an event already exists for this date
        $existingEvent = $this->findEventByDate($dateOnly);

        if ($existingEvent !== null) {
            return $existingEvent;
        }

        // Create a new auto-generated event
        return $this->createAutoEvent($dateOnly);
    }

    /**
     * Syncs a reservation to its corresponding event.
     * Creates the event if it doesn't exist, then syncs all guests.
     */
    public function syncReservationToEvent(Reservation $reservation): Event
    {
        $event = $this->ensureEventForDate($reservation->getDate());

        // Sync all guests from all reservations for this date
        $this->guestSyncService->syncForEvent($event);

        // Update event guest counts based on reservations
        $this->updateEventGuestCounts($event);

        return $event;
    }

    /**
     * Called when a reservation is deleted.
     * Re-syncs the event for that date (or removes it if no reservations remain).
     */
    public function handleReservationDeleted(\DateTimeInterface $date): void
    {
        $dateOnly = \DateTime::createFromInterface($date)->setTime(0, 0, 0);
        $event = $this->findEventByDate($dateOnly);

        if ($event === null) {
            return;
        }

        // Check if any reservations remain for this date
        $remainingReservations = $this->em->getRepository(Reservation::class)
            ->findBy(['date' => $dateOnly]);

        if (count($remainingReservations) === 0 && $event->isAutoGenerated()) {
            // No reservations left and event was auto-generated - remove it
            $this->em->remove($event);
            $this->em->flush();
            return;
        }

        // Re-sync guests for remaining reservations
        $this->guestSyncService->syncForEvent($event);
        $this->updateEventGuestCounts($event);
    }

    /**
     * Finds an event by date.
     */
    private function findEventByDate(\DateTimeInterface $date): ?Event
    {
        return $this->em->createQueryBuilder()
            ->select('e')
            ->from(Event::class, 'e')
            ->where('e.eventDate = :date')
            ->setParameter('date', $date)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Creates a new auto-generated event for the given date.
     */
    private function createAutoEvent(\DateTimeInterface $date): Event
    {
        $event = new Event();

        // Determine event type based on day of week
        $dayOfWeek = (int) $date->format('N'); // 1 = Monday, 7 = Sunday
        $isWeekend = $dayOfWeek >= 6;

        $event
            ->setName($this->generateEventName($date))
            ->setEventType($isWeekend ? 'FOLKLORE_SHOW' : 'FOLKLORE_SHOW')
            ->setEventDate($date)
            ->setEventTime(new \DateTime('18:00:00'))
            ->setDurationMinutes(180)
            ->setStatus('DRAFT')
            ->setIsAutoGenerated(true)
            ->setLanguage('CZ')
            ->setVenue('ROUBENKA');

        $this->em->persist($event);
        $this->em->flush();

        return $event;
    }

    /**
     * Generates a default event name based on the date.
     */
    private function generateEventName(\DateTimeInterface $date): string
    {
        $dayNames = [
            1 => 'Pondělí',
            2 => 'Úterý',
            3 => 'Středa',
            4 => 'Čtvrtek',
            5 => 'Pátek',
            6 => 'Sobota',
            7 => 'Neděle',
        ];

        $dayOfWeek = (int) $date->format('N');
        $dayName = $dayNames[$dayOfWeek] ?? '';
        $formattedDate = $date->format('j.n.Y');

        return "Folklórní večer - {$dayName} {$formattedDate}";
    }

    /**
     * Updates event guest counts based on all reservations for that date.
     *
     * Počítání hostů zohledňuje stav platby rezervace:
     * - guestsPaid = hosté ze ZAPLACENÝCH rezervací (adults, guides, drivers)
     * - guestsFree = děti/kojenci + nezaplacení dospělí
     *
     * Toto umožňuje přesné plánování eventu na základě skutečně potvrzených (zaplacených) hostů.
     */
    private function updateEventGuestCounts(Event $event): void
    {
        $reservations = $this->em->getRepository(Reservation::class)
            ->findBy(['date' => $event->getEventDate()]);

        $totalPaid = 0;
        $totalFree = 0;

        foreach ($reservations as $reservation) {
            // Zkontroluj zda je rezervace zaplacená
            $isPaid = $this->isReservationPaid($reservation);

            foreach ($reservation->getPersons() as $person) {
                $type = $person->getType();

                // Děti a kojenci jsou vždy free
                if ($type === 'child' || $type === 'infant') {
                    $totalFree++;
                    continue;
                }

                // Dospělí, průvodci a řidiči
                if ($type === 'adult' || $type === 'guide' || $type === 'driver') {
                    if ($isPaid) {
                        // Zaplacená rezervace - počítej jako paid
                        $totalPaid++;
                    } else {
                        // Nezaplacená rezervace - počítej jako free (očekávaní hosté)
                        $totalFree++;
                    }
                }
            }
        }

        $event->setGuestsPaid($totalPaid);
        $event->setGuestsFree($totalFree);

        $this->em->flush();
    }

    /**
     * Zkontroluje, zda je rezervace považována za zaplacenou.
     *
     * Rezervace je zaplacená pokud:
     * - paymentStatus = 'PAID', nebo
     * - paidAmount >= totalPrice (plně uhrazeno)
     */
    private function isReservationPaid(Reservation $reservation): bool
    {
        // Kontrola paymentStatus
        if ($reservation->getPaymentStatus() === 'PAID') {
            return true;
        }

        // Kontrola skutečně zaplacené částky
        $totalPrice = (float)($reservation->getTotalPrice() ?? 0);
        $paidAmount = (float)($reservation->getPaidAmount() ?? 0);

        if ($totalPrice > 0 && $paidAmount >= $totalPrice) {
            return true;
        }

        // Starý způsob - kontrola statusu rezervace (zpětná kompatibilita)
        if ($reservation->getStatus() === 'PAID') {
            return true;
        }

        return false;
    }
}
