<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
#[ORM\Table(name: 'event')]
#[ORM\HasLifecycleCallbacks]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $name;

    #[ORM\Column(type: Types::STRING, length: 50)]
    private string $eventType; // 'FOLKLORE_SHOW', 'WEDDING', 'PRIVATE_EVENT', 'CORPORATE'

    #[ORM\ManyToOne(targetEntity: Reservation::class)]
    #[ORM\JoinColumn(name: 'reservation_id', referencedColumnName: 'id', nullable: true, onDelete: 'SET NULL')]
    private ?Reservation $reservation = null;

    // Základní údaje
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private \DateTimeInterface $eventDate;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private \DateTimeInterface $eventTime;

    #[ORM\Column(type: Types::INTEGER, options: ['default' => 120])]
    private int $durationMinutes = 120;

    // Počet osob
    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $guestsPaid = 0;

    #[ORM\Column(type: Types::INTEGER, nullable: true, options: ['default' => 0])]
    private ?int $guestsFree = 0;

    // Doctrine doesn’t support generated stored column portably; keep as cached value
    #[ORM\Column(type: Types::INTEGER, options: ['default' => 0])]
    private int $guestsTotal = 0;

    // Místo konání
    #[ORM\Column(type: Types::STRING, length: 100, nullable: true)]
    private ?string $venue = null; // 'ROUBENKA', 'TERASA', ...

    // Kontaktní údaje organizátora
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $organizerCompany = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $organizerPerson = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $organizerEmail = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $organizerPhone = null;

    // Jazykové verze
    #[ORM\Column(type: Types::STRING, length: 10, options: ['default' => 'CZ'])]
    private string $language = 'CZ';

    // Fakturační údaje
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $invoiceCompany = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $invoiceIc = null;

    #[ORM\Column(type: Types::STRING, length: 20, nullable: true)]
    private ?string $invoiceDic = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $invoiceAddress = null;

    // Platba
    #[ORM\Column(type: Types::DECIMAL, precision: 15, scale: 2, nullable: true)]
    private ?string $totalPrice = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 15, scale: 2, nullable: true)]
    private ?string $depositAmount = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $depositPaid = false;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $paymentMethod = null; // 'CASH', 'BANK_TRANSFER', 'CARD', 'INVOICE'

    // Status
    #[ORM\Column(type: Types::STRING, length: 50, options: ['default' => 'PLANNED'])]
    private string $status = 'PLANNED';

    // Subkategorie a tagy
    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $eventSubcategory = null; // 'obedy', 'vecere', 'privat', 'show', 'firemni', 'other'

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $eventTags = null;

    // Catering
    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $cateringType = null; // 'vlastni', 'ventura', 'folkloregarden'

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2, nullable: true)]
    private ?string $cateringCommissionPercent = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 15, scale: 2, nullable: true)]
    private ?string $cateringCommissionAmount = null;

    // Auto-generated flag
    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $isAutoGenerated = false;

    // Poznámky
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notesStaff = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notesInternal = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $specialRequirements = null;

    // Metadata
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'created_by', referencedColumnName: 'id', nullable: true, onDelete: 'SET NULL')]
    private ?User $createdBy = null;

    // Koordinátor - může být interní (z personálu) nebo externí
    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $coordinatorId = null; // ID z tabulky staff_member (interní)

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private bool $isExternalCoordinator = false;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $externalCoordinatorName = null;

    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    private ?string $externalCoordinatorEmail = null;

    #[ORM\Column(type: Types::STRING, length: 50, nullable: true)]
    private ?string $externalCoordinatorPhone = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $externalCoordinatorNote = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $createdAt;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTimeInterface $updatedAt;

    // Relations to child tables
    /** @var Collection<int, EventGuest> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventGuest::class, cascade: ['persist', 'remove'])]
    private Collection $guests;

    /** @var Collection<int, EventMenu> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventMenu::class, cascade: ['persist', 'remove'])]
    private Collection $menus;

    /** @var Collection<int, EventBeverage> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventBeverage::class, cascade: ['persist', 'remove'])]
    private Collection $beverages;

    /** @var Collection<int, EventStaffAssignment> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventStaffAssignment::class, cascade: ['persist', 'remove'])]
    private Collection $staffAssignments;

    /** @var Collection<int, EventSchedule> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventSchedule::class, cascade: ['persist', 'remove'])]
    private Collection $schedules;

    /** @var Collection<int, EventVoucher> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventVoucher::class, cascade: ['persist', 'remove'])]
    private Collection $vouchers;

    /** @var Collection<int, EventTable> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventTable::class, cascade: ['persist', 'remove'])]
    private Collection $tables;

    /** @var Collection<int, EventSpace> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventSpace::class, cascade: ['persist', 'remove'])]
    private Collection $spaces;

    /** @var Collection<int, EventInvoice> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventInvoice::class, cascade: ['persist', 'remove'])]
    private Collection $eventInvoices;

    /** @var Collection<int, FloorPlanElement> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: FloorPlanElement::class, cascade: ['persist', 'remove'])]
    private Collection $floorPlanElements;

    /** @var Collection<int, EventTransport> */
    #[ORM\OneToMany(mappedBy: 'event', targetEntity: EventTransport::class, cascade: ['persist', 'remove'])]
    private Collection $transportAssignments;

    public function __construct()
    {
        $this->guests = new ArrayCollection();
        $this->menus = new ArrayCollection();
        $this->beverages = new ArrayCollection();
        $this->staffAssignments = new ArrayCollection();
        $this->schedules = new ArrayCollection();
        $this->vouchers = new ArrayCollection();
        $this->tables = new ArrayCollection();
        $this->spaces = new ArrayCollection();
        $this->eventInvoices = new ArrayCollection();
        $this->floorPlanElements = new ArrayCollection();
        $this->transportAssignments = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTime();
        $this->createdAt = $this->createdAt ?? $now;
        $this->updatedAt = $now;
        $this->recalcGuestsTotal();
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTime();
        $this->recalcGuestsTotal();
    }

    private function recalcGuestsTotal(): void
    {
        $this->guestsTotal = (int)($this->guestsPaid ?? 0) + (int)($this->guestsFree ?? 0);
    }

    // Getters/setters (subset for required operations)
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getEventType(): string
    {
        return $this->eventType;
    }

    public function setEventType(string $eventType): self
    {
        $this->eventType = $eventType;
        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(?Reservation $reservation): self
    {
        $this->reservation = $reservation;
        return $this;
    }

    public function getEventDate(): \DateTimeInterface
    {
        return $this->eventDate;
    }

    public function setEventDate(\DateTimeInterface $eventDate): self
    {
        $this->eventDate = $eventDate;
        return $this;
    }

    public function getEventTime(): \DateTimeInterface
    {
        return $this->eventTime;
    }

    public function setEventTime(\DateTimeInterface $eventTime): self
    {
        $this->eventTime = $eventTime;
        return $this;
    }

    public function getDurationMinutes(): int
    {
        return $this->durationMinutes;
    }

    public function setDurationMinutes(int $minutes): self
    {
        $this->durationMinutes = $minutes;
        return $this;
    }

    public function getGuestsPaid(): int
    {
        return $this->guestsPaid;
    }

    public function setGuestsPaid(int $v): self
    {
        $this->guestsPaid = $v;
        $this->recalcGuestsTotal();
        return $this;
    }

    public function getGuestsFree(): ?int
    {
        return $this->guestsFree;
    }

    public function setGuestsFree(?int $v): self
    {
        $this->guestsFree = $v;
        $this->recalcGuestsTotal();
        return $this;
    }

    public function getGuestsTotal(): int
    {
        return $this->guestsTotal;
    }

    public function isAutoGenerated(): bool
    {
        return $this->isAutoGenerated;
    }

    public function setIsAutoGenerated(bool $v): self
    {
        $this->isAutoGenerated = $v;
        return $this;
    }

    public function getVenue(): ?string
    {
        return $this->venue;
    }

    public function setVenue(?string $v): self
    {
        $this->venue = $v;
        return $this;
    }

    public function getOrganizerCompany(): ?string
    {
        return $this->organizerCompany;
    }

    public function setOrganizerCompany(?string $v): self
    {
        $this->organizerCompany = $v;
        return $this;
    }

    public function getOrganizerPerson(): ?string
    {
        return $this->organizerPerson;
    }

    public function setOrganizerPerson(?string $v): self
    {
        $this->organizerPerson = $v;
        return $this;
    }

    public function getOrganizerEmail(): ?string
    {
        return $this->organizerEmail;
    }

    public function setOrganizerEmail(?string $v): self
    {
        $this->organizerEmail = $v;
        return $this;
    }

    public function getOrganizerPhone(): ?string
    {
        return $this->organizerPhone;
    }

    public function setOrganizerPhone(?string $v): self
    {
        $this->organizerPhone = $v;
        return $this;
    }

    public function getLanguage(): string
    {
        return $this->language;
    }

    public function setLanguage(string $v): self
    {
        $this->language = $v;
        return $this;
    }

    public function getInvoiceCompany(): ?string
    {
        return $this->invoiceCompany;
    }

    public function setInvoiceCompany(?string $v): self
    {
        $this->invoiceCompany = $v;
        return $this;
    }

    public function getInvoiceIc(): ?string
    {
        return $this->invoiceIc;
    }

    public function setInvoiceIc(?string $v): self
    {
        $this->invoiceIc = $v;
        return $this;
    }

    public function getInvoiceDic(): ?string
    {
        return $this->invoiceDic;
    }

    public function setInvoiceDic(?string $v): self
    {
        $this->invoiceDic = $v;
        return $this;
    }

    public function getInvoiceAddress(): ?string
    {
        return $this->invoiceAddress;
    }

    public function setInvoiceAddress(?string $v): self
    {
        $this->invoiceAddress = $v;
        return $this;
    }

    public function getTotalPrice(): ?string
    {
        return $this->totalPrice;
    }

    public function setTotalPrice(?string $v): self
    {
        $this->totalPrice = $v;
        return $this;
    }

    public function getDepositAmount(): ?string
    {
        return $this->depositAmount;
    }

    public function setDepositAmount(?string $v): self
    {
        $this->depositAmount = $v;
        return $this;
    }

    public function isDepositPaid(): bool
    {
        return $this->depositPaid;
    }

    public function setDepositPaid(bool $v): self
    {
        $this->depositPaid = $v;
        return $this;
    }

    public function getPaymentMethod(): ?string
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(?string $v): self
    {
        $this->paymentMethod = $v;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $v): self
    {
        $this->status = $v;
        return $this;
    }

    public function getEventSubcategory(): ?string
    {
        return $this->eventSubcategory;
    }

    public function setEventSubcategory(?string $v): self
    {
        $this->eventSubcategory = $v;
        return $this;
    }

    public function getEventTags(): ?array
    {
        return $this->eventTags;
    }

    public function setEventTags(?array $v): self
    {
        $this->eventTags = $v;
        return $this;
    }

    public function getCateringType(): ?string
    {
        return $this->cateringType;
    }

    public function setCateringType(?string $v): self
    {
        $this->cateringType = $v;
        return $this;
    }

    public function getCateringCommissionPercent(): ?string
    {
        return $this->cateringCommissionPercent;
    }

    public function setCateringCommissionPercent(?string $v): self
    {
        $this->cateringCommissionPercent = $v;
        return $this;
    }

    public function getCateringCommissionAmount(): ?string
    {
        return $this->cateringCommissionAmount;
    }

    public function setCateringCommissionAmount(?string $v): self
    {
        $this->cateringCommissionAmount = $v;
        return $this;
    }

    public function getNotesStaff(): ?string
    {
        return $this->notesStaff;
    }

    public function setNotesStaff(?string $v): self
    {
        $this->notesStaff = $v;
        return $this;
    }

    public function getNotesInternal(): ?string
    {
        return $this->notesInternal;
    }

    public function setNotesInternal(?string $v): self
    {
        $this->notesInternal = $v;
        return $this;
    }

    public function getSpecialRequirements(): ?string
    {
        return $this->specialRequirements;
    }

    public function setSpecialRequirements(?string $v): self
    {
        $this->specialRequirements = $v;
        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $u): self
    {
        $this->createdBy = $u;
        return $this;
    }

    public function getCoordinatorId(): ?int
    {
        return $this->coordinatorId;
    }

    public function setCoordinatorId(?int $v): self
    {
        $this->coordinatorId = $v;
        return $this;
    }

    public function isExternalCoordinator(): bool
    {
        return $this->isExternalCoordinator;
    }

    public function setIsExternalCoordinator(bool $v): self
    {
        $this->isExternalCoordinator = $v;
        return $this;
    }

    public function getExternalCoordinatorName(): ?string
    {
        return $this->externalCoordinatorName;
    }

    public function setExternalCoordinatorName(?string $v): self
    {
        $this->externalCoordinatorName = $v;
        return $this;
    }

    public function getExternalCoordinatorEmail(): ?string
    {
        return $this->externalCoordinatorEmail;
    }

    public function setExternalCoordinatorEmail(?string $v): self
    {
        $this->externalCoordinatorEmail = $v;
        return $this;
    }

    public function getExternalCoordinatorPhone(): ?string
    {
        return $this->externalCoordinatorPhone;
    }

    public function setExternalCoordinatorPhone(?string $v): self
    {
        $this->externalCoordinatorPhone = $v;
        return $this;
    }

    public function getExternalCoordinatorNote(): ?string
    {
        return $this->externalCoordinatorNote;
    }

    public function setExternalCoordinatorNote(?string $v): self
    {
        $this->externalCoordinatorNote = $v;
        return $this;
    }

    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeInterface
    {
        return $this->updatedAt;
    }

    /** @return Collection<int, EventGuest> */
    public function getGuests(): Collection
    {
        return $this->guests;
    }

    public function addGuest(EventGuest $g): self
    {
        if (!$this->guests->contains($g)) {
            $this->guests->add($g);
            $g->setEvent($this);
        }
        return $this;
    }

    public function removeGuest(EventGuest $g): self
    {
        if ($this->guests->removeElement($g)) {
            if ($g->getEvent() === $this) {
                $g->setEvent(null);
            }
        }
        return $this;
    }

    /** @return Collection<int, EventMenu> */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    /** @return Collection<int, EventBeverage> */
    public function getBeverages(): Collection
    {
        return $this->beverages;
    }

    /** @return Collection<int, EventStaffAssignment> */
    public function getStaffAssignments(): Collection
    {
        return $this->staffAssignments;
    }

    /** @return Collection<int, EventSchedule> */
    public function getSchedules(): Collection
    {
        return $this->schedules;
    }

    /** @return Collection<int, EventVoucher> */
    public function getVouchers(): Collection
    {
        return $this->vouchers;
    }

    /** @return Collection<int, EventTable> */
    public function getTables(): Collection
    {
        return $this->tables;
    }

    public function addTable(EventTable $table): self
    {
        if (!$this->tables->contains($table)) {
            $this->tables->add($table);
            $table->setEvent($this);
        }
        return $this;
    }

    public function removeTable(EventTable $table): self
    {
        if ($this->tables->removeElement($table)) {
            if ($table->getEvent() === $this) {
                $table->setEvent(null);
            }
        }
        return $this;
    }

    /** @return Collection<int, EventSpace> */
    public function getSpaces(): Collection
    {
        return $this->spaces;
    }

    /** @return Collection<int, EventInvoice> */
    public function getEventInvoices(): Collection
    {
        return $this->eventInvoices;
    }

    /** @return Collection<int, FloorPlanElement> */
    public function getFloorPlanElements(): Collection
    {
        return $this->floorPlanElements;
    }

    /** @return Collection<int, EventTransport> */
    public function getTransportAssignments(): Collection
    {
        return $this->transportAssignments;
    }

    public function addFloorPlanElement(FloorPlanElement $el): self
    {
        if (!$this->floorPlanElements->contains($el)) {
            $this->floorPlanElements->add($el);
            $el->setEvent($this);
        }
        return $this;
    }

    public function removeFloorPlanElement(FloorPlanElement $el): self
    {
        if ($this->floorPlanElements->removeElement($el)) {
            if ($el->getEvent() === $this) {
                $el->setEvent(null);
            }
        }
        return $this;
    }
}
